// Code generated by "stringer -type=CardName"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Librarian-1]
	_ = x[Magician-2]
	_ = x[Shieldmancer-3]
	_ = x[MindMage-4]
	_ = x[Angel-5]
	_ = x[Pyromancer-6]
	_ = x[Bloodeater-7]
	_ = x[Conjurer-8]
	_ = x[Mortician-9]
	_ = x[Protectio-10]
	_ = x[PyrusBalio-11]
	_ = x[Mortius-12]
	_ = x[Enhancius-13]
	_ = x[Dragonius-14]
	_ = x[Cancelio-15]
	_ = x[Conjorius-16]
	_ = x[AngeliDustio-17]
	_ = x[Vitalius-18]
	_ = x[Dralio-19]
	_ = x[Librarius-20]
	_ = x[Aquarius-21]
	_ = x[Bubublius-22]
	_ = x[Meteorus-23]
	_ = x[Armorius-24]
	_ = x[DracusPyrio-25]
	_ = x[Retrievio-26]
	_ = x[Extractio-27]
}

const _CardName_name = "NoneLibrarianMagicianShieldmancerMindMageAngelPyromancerBloodeaterConjurerMorticianProtectioPyrusBalioMortiusEnhanciusDragoniusCancelioConjoriusAngeliDustioVitaliusDralioLibrariusAquariusBububliusMeteorusArmoriusDracusPyrioRetrievioExtractio"

var _CardName_index = [...]uint8{0, 4, 13, 21, 33, 41, 46, 56, 66, 74, 83, 92, 102, 109, 118, 127, 135, 144, 156, 164, 170, 179, 187, 196, 204, 212, 223, 232, 241}

func (i CardName) String() string {
	if i < 0 || i >= CardName(len(_CardName_index)-1) {
		return "CardName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardName_name[_CardName_index[i]:_CardName_index[i+1]]
}
